<?php

declare(strict_types=1);

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Models\Ticket;
use App\Models\TicketMedia;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * Ticket Evidence Privacy Proxy.
 *
 * Authorization gates enforced on every request:
 *   1. Authenticated user (middleware).
 *   2. User can view the parent ticket (TicketPolicy@view).
 *   3. Media belongs to that ticket (404 if not).
 *
 * Resolution strategy:
 *   a. If file_url is a localhost/APP_URL-based path and the file exists on the
 *      local public disk, stream it directly (works in local dev).
 *   b. Otherwise, redirect to the stored URL (Supabase public URL in production).
 *
 * Returns 404 for every gate failure; no distinguishing messages are exposed.
 */
class TicketMediaViewController extends Controller
{
    public function __invoke(Ticket $ticket, TicketMedia $media): RedirectResponse|StreamedResponse
    {
        $this->authorize('view', $ticket);

        if ((string) $media->ticket_id !== (string) $ticket->id) {
            abort(404);
        }

        $fileUrl = trim((string) ($media->file_url ?? ''));
        if ($fileUrl === '') {
            abort(404);
        }

        $localPath = $this->localPublicPath($fileUrl);
        if ($localPath !== null) {
            if (! Storage::disk('public')->exists($localPath)) {
                abort(404);
            }

            return $this->streamFromPublicDisk($localPath, (string) ($media->file_type ?? ''));
        }

        if (filter_var($fileUrl, FILTER_VALIDATE_URL)) {
            return redirect()->away($fileUrl);
        }

        abort(404);
    }

    /**
     * Extracts a relative storage path from a URL generated by
     * Storage::disk('public')->url($path). Returns null for Supabase or
     * other non-local URLs so they fall through to the redirect branch.
     */
    private function localPublicPath(string $fileUrl): ?string
    {
        $appUrl = rtrim((string) config('app.url'), '/');
        $storageBase = $appUrl.'/storage/';

        if ($appUrl !== '' && str_starts_with($fileUrl, $storageBase)) {
            return substr($fileUrl, strlen($storageBase));
        }

        if (! str_starts_with($fileUrl, 'http://') && ! str_starts_with($fileUrl, 'https://')) {
            return ltrim($fileUrl, '/');
        }

        return null;
    }

    private function streamFromPublicDisk(string $path, string $mimeType): StreamedResponse
    {
        $bytes = Storage::disk('public')->get($path);
        if (! is_string($bytes) || $bytes === '') {
            abort(404);
        }

        $contentType = $mimeType !== '' ? $mimeType : 'application/octet-stream';
        $body = $bytes;

        return response()->stream(
            static function () use ($body): void {
                echo $body;
            },
            200,
            [
                'Content-Type' => $contentType,
                'Cache-Control' => 'private, max-age=300',
                'X-Content-Type-Options' => 'nosniff',
                'Content-Disposition' => 'inline',
            ],
        );
    }
}
