name: Tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        # OWASP: Se fija la versión usando un hash SHA en lugar de tags mutables como "v4"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup PHP
        # OWASP: Se fija la versión usando un hash SHA en lugar de tags mutables como "v2"
        uses: shivammathur/setup-php@b7dfee87981ef78d0aa00ae72a29ea9796e9cbbe # v2.30.4
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
        env:
          APP_ENV: testing

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Execute tests
        run: vendor/bin/phpunit
