name: Update Changelog

on:
  release:
    types: [released]

permissions: {}

jobs:
  update:
    permissions:
      contents: write
    # OWASP/SonarCloud: Evitar referenciar ramas mutables como "main" o "master"
    uses: laravel/.github/.github/workflows/update-changelog.yml@b6f4cc920b7ba40fa0fa82cd93dd09d43ed0b5b2
